config/routes.rb
LyricalMiracle::Application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'
  
  devise_for :users, :controllers => {
    :sessions => 'sessions', 
    :registrations => 'registrations',
    :omniauth_callbacks => 'omniauth_callbacks'
  }

  root :to => "index#index"
  # devise_for :users
  get "songs/artists", :to => "songs#artists"
  
  resources :songs
  resources :annotations
  
end

app/models/annotation.rb
class Annotation < ActiveRecord::Base
  attr_accessible :body, :song_id, :user_id
  validates :body, :user_id, :song_id, :presence => true
  
  belongs_to :user
  belongs_to :song
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :link, :name, :provider, :secret, :token, :uid, :user_id
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :album_title, :artist, :body, :title, :user_id, :youtube_link
  
  validates :artist, :body, :title, :presence => true
  has_many :annotations
  
  def clean_lyrics_create
    unclean_lyrics = self.body
    clean_lyrics = Sanitize.clean(unclean_lyrics, 
      :elements => ['br'],
      :remove_contents => false
    )
    self.body = clean_lyrics.gsub("'", "&#39;").gsub("\n", "").gsub("\r", "")
  end
  
  def clean_lyrics_update
    unclean_lyrics = self.body
    clean_lyrics = Sanitize.clean(unclean_lyrics, 
      :elements => ['a', 'br'],
      :attributes => {'a' => ['href', 'class', 'id']},
      :add_attributes => { 'a' => { 'href' => '#'} },
      # :protocols => {'a' => {'href' => ['#']}},
      :remove_contents => false
    )
    self.body = clean_lyrics.strip.gsub("'", "&#39;").gsub("\n", "").gsub("\r", "")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :omniauthable,
           :recoverable, :rememberable, :trackable, :validatable, :omniauth_providers => [:google_oauth2]
           
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :provider, :uid
  
  def self.from_omniauth(auth)
    if user = User.find_by_email(auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user
    else
      user = User.new
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.save
      user
    end
  end
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    @annotation = Annotation.new(params[:annotation])
    @annotation.user_id = current_user.id
    @annotation.save
    render :json => @annotation
  end
  
  def update
    @annotation = Annotation.find(params[:id])
    @annotation.update_attributes(params[:annotation])
    render :json => @annotation
  end
  
  def destroy
    @annotation = Annotation.find(params[:id])
    @annotation.destroy
    render :json => @annotation
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
  
  def after_sign_up_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    render :index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user
      sign_in(@user)
      #this only has to happen on sign up for some reason
      warden.set_user @user
      redirect_to request.env['omniauth.origin']
    else
      render :json => {:success => false, :errors => "Login Failed. Please try again."}, :status => 422
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  include ApplicationsHelper

  def create
    build_resource(params[:user])
    
    if resource.save
      sign_in(:user, resource)
      render :json => {:resource => resource}
    else
      render :json => {:errors => resource.errors.full_messages.to_sentence}, :status => 422
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def new
    redirect_to root_url
  end
  
  def create
    resource = warden.authenticate!(:scope => resource_name, :recall => 'sessions#failure')
    sign_in_and_redirect(resource_name, resource)
  end

  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource
    render :json => {:success => true}
  end

  def failure
    render :json => {:success => false, :errors => "Login failed. Please try again."}, :status => 422
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :artists, :show]
  
  def index
    if params[:song] && params[:song][:search_query]
      @is_search = true
      @query = params[:song][:search_query]
      search = "%" + params[:song][:search_query] + "%"
      @songs = Song.where(<<-SQL, search, search)
        UPPER(title) LIKE UPPER(?) OR UPPER(artist) LIKE UPPER(?)
        SQL
      render :index
    else  
      @songs = Song.all
      @song = Song.last
      @song_titles = Song.pluck(:title)
    
      respond_to do |format|
        format.html {render :index}
        format.json { render :json => @song_titles.to_json }
      end
    end
  end
  
  def artists
    @artists = Song.pluck(:artist).uniq
    
    respond_to do |format|
      format.json { render :json => @artists.to_json }
    end
  end
  
  def show
    @song = Song.find(params[:id])
  end
  
  def new
    @song = Song.new
    render :new
  end
  
  def edit
    @song = Song.find(params[:id])
    render :edit
  end
  
  def create
    @song = Song.new(params[:song])
    @song.clean_lyrics_create
    @song.body.squish
    
    if @song.save
      redirect_to song_url(@song)
    else
      flash[:errors] = []
      flash.now[:errors] << @song.errors.full_messages.to_sentence
      render :new
    end
  end
  
  def update
    #originally had way to stop editing in DOM from song display page
    #from getting saved, but removed because I thought it was overkill
    #considering anyone is allowed to edit a song anyway
    @song = Song.find(params[:id])
    @song.body = params[:song][:body]
    @song.title = params[:song][:title]
    @song.artist = params[:song][:artist]
    clean_song(@song)

    if @song.save
      respond_to do |format|
        format.json { render :json => @song }
        format.html { redirect_to song_url(@song) }
      end
    else
      respond_to do |format|
        format.json { render :json => { :errors => @song.errors.full_messages } }
        format.html do
          flash[:errors] = []
          flash.now[:errors] << @song.errors.full_messages.to_sentence
          render :edit
        end
      end
    end
  end
  
  
  def clean_song(song)
    song.clean_lyrics_update
    song.body.squish
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :redirect_logged_in_user, :only => [:new]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      login_user(@user)
      redirect_to @user
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << @user.errors.full_messages.to_sentence
      render :new
    end
  end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
  def resource_name
    :user
  end
 
  # def resource
 #    @resource ||= User.new
 #  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/index.html.erb
<% title = ["L","y","r","i","c","a","l","M","i","r","a","c","l","e"]%>

<div class="container">
	<div id="index-title-container">
		<% title.each_with_index do |chr, idx| %>
		<% if idx == 0 || idx == 7 %>
			<div class="index-title-chunk"> 
		<%end%>
		<span class="index-title" id="index-title-<%=idx%>"><%=chr%></span>
		<% if idx == 6 || idx == 13 %>
			</div> 
		<%end%>
		<% end %>
	</div>
	<h3>Discover the meaning of lyrics, add what you know, and see what others are saying. Get started by browsing all songs, searching for your favorite,
        <a class="accordion-toggle intro-link" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          or watching a short introduction
        </a>.
	</h3>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body">
<iframe width="640" height="480" src="//www.youtube.com/embed/Xd7d2RHRGcM" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>
</div>


<script>
$(document).ready(function () {
	for(var i = 0; i < 14; i++) {
		$('#index-title-' + i).on('mouseover', function () {
			var colors = ['red', 'yellow', 'pink', 'green', 'blue'];
			var rand = Math.floor(Math.random() * 6);
			$(this).attr("class", "index-title " + colors[rand]);
		});
	}
})
</script>

app/views/layouts/_login.html.erb
<div class="modal" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="login-modal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header no-line">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
				<ul class="nav nav-tabs">
				  <li class="active">
						<a href="#login-form-content" data-toggle="tab">Log In</a>
					</li>
				  <li><a href="#sign-up-form-content" data-toggle="tab">Sign up!</a></li>
				</ul>
       
			  <div id="login-modal-body" class="modal-body">
					
						<div id="login-errors" class="alert alert-warning">
						</div>
	
					<div class="login-l" id="google-sign-in">
						<a href="<%= user_omniauth_authorize_path(:google_oauth2) %>">
						<img src="/images/google_sign_in.png" alt="Sign in with Google" title="SIgn in with Google" height=60></a>
					</div>
					<br>
					
				<div class="tab-content">
				  <div class="tab-pane active" id="login-form-content">
						<small><em>or sign in with your Lyrical Miracle account:</em></small>
						<form role="form" id="login-form">
							<div class="form-group">
								<label for="user_email">Email</label>
								<input class="form-control" type="text" name="user[email]" id="user_email" placeholder="email">
							</div>
							<div class="form-group">
								<label for="user_password">Password</label>
								<input class="form-control" type="password" id="user_password" name="user[password]" placeholder="password">
							</div>
			        <div class="modal-footer">
			          <button type="submit" class="btn btn-primary login-l">Submit</button>
			        </div>
						</form>
					</div>
				  <div class="tab-pane" id="sign-up-form-content">
						<small><em>or create a new Lyrical Miracle account:</em></small>
						<form id="signup-form">
							<div class="form-group">
								<label for="sign_user_email">Email</label>
								<input class="form-control" type="text" name="user[email]" id="sign_user_email" placeholder="email">
							</div>
							<div class="form-group">
								<label for="sign_user_password">Password</label>
								<input class="form-control" type="password" id="sign_user_password" name="user[password]" placeholder="password">
							</div>
							<div class="form-group">
								<label for="sign_user_password_confirmation">Password Confirmation</label>
								<input class="form-control" type="password" id="sign_user_password_confirmation" name="user[password_confirmation]" placeholder="password confirmation">
							</div>
			        <div class="modal-footer">
			          <button type="submit" class="btn btn-primary login-l">Submit</button>
			        </div>
						</form>
					</div>
				</div>
			</div>
	
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/layouts/_navbar.html.erb
<div id="body-container">
	<nav class="navbar navbar-default navbar-fixed">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <a class="navbar-brand" href="<%= root_url %>">LyricalMiracle</a>
	  </div>
	  <div class="collapse navbar-collapse">
	    <ul class="nav navbar-nav">
				<li><a href= '#' class="invisible">l</a></li>
				<li class="dropdown">
				  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Songs
									<b class="caret"></b></a>
				<ul class="dropdown-menu">
		      <li>
						<a id="add-song-button" href="<%= new_song_url %>">Add Song</a>
					</li>
		      <li><a href="<%= songs_url %>">All Songs</a></li>
				</ul>
			</li>
			<li><a href= '#' class="invisible">l</a></li>
	    </ul>
			
	    <form class="navbar-form navbar-left search-bar" role="search" action="<%= songs_url %>" method="GET">
	      <div class="form-group">
	        <input id="song-search" name="song[search_query]" type="text" class="form-control" placeholder="Search by title or artist">
	      </div>

	      <button type="submit" class="btn btn-default mag-glass"><span class="glyphicon glyphicon-search"></span></button>
	    </form>
	    <ul id="authentication-bar" class="nav navbar-nav navbar-right">
				<% if current_user %>
	      	<li><p class="navbar-text" id="user-email"><%= current_user.email %></li>
					<li><a href="#" id="log-out">Log Out</a></li>
					<li><a href="#" class="invisible" id="log-in">Log In</a></li>
				<% else %>
	      	<li><a href="#" class="invisible" id="user-email"></a></li>
					<li><a href="#" class="invisible" id="log-out">Log Out</a></li>
					<li><a href="#" id="log-in">Log In</a></li>
				<% end %>
	    </ul>
	  </div><!-- /.navbar-collapse -->
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LyricalMiracle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
	<body>
	
		<%= render "layouts/navbar" %>
	
			<div id="main-container">
		  	<%= yield %>
			</div>

		<%= render "layouts/login" %>


	</body>
</html>

app/views/songs/_form.html.erb
	<input type="hidden" name="authenticity_token"
											 value="<%= form_authenticity_token %>">
	
  <div class="form-group">
		<label for="song_title">Title</label>
		<input class="form-control" type="text" id="song_title" name="song[title]" value="<%= song.title %>">
  </div>
  <div class="form-group">
		<label for="song_artist">Artist</label>
		<input class="form-control" type="text" id="song_artist" 						                   name="song[artist]"value="<%= song.artist %>">
  </div>
  <div class="form-group">
		<label for="song_album">Album</label>
		<input class="form-control" type="text" id="song_album" name="song[album_title]" value="<%= song.album_title %>">
  </div>
	<div class="form-group">
		<label for="song_lyrics">Lyrics</label>
		<textarea class="form-control" cols="100" rows="10" id="song_lyrics_form" name="song[body]"></textarea>
	</div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>


<script>
$(document).ready( function() { 
	for(name in CKEDITOR.instances) {
	    CKEDITOR.instances[name].destroy()
	}
	CKEDITOR.replace($('#song_lyrics_form').get(0), {"height":300,"stylesSet":[],"extraPlugins":"stylesheetparser,richfile,MediaEmbed,smiley","removePlugins":"scayt,menubutton,image,forms,elementspath,magicline","contentsCss":"/assets/rich/editor.css","removeDialogTabs":"link:advanced;link:target","startupOutlineBlocks":false,"forcePasteAsPlainText":true,"format_tags":"h3;p;pre","toolbar": [],"enterMode": CKEDITOR.ENTER_BR,"language":"en","richBrowserUrl":"/rich/files/","uiColor":"#f4f4f4","allowed_styles":["thumb","rich_thumb","original"],"default_style":"thumb","insert_many":false,"allow_document_uploads":false,"allow_embeds":false,"placeholder_image":"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==","preview_size":"100px","hidden_input":false});

	CKEDITOR.instances.song_lyrics_form.setData('<%= @song.body.gsub("\n", "").gsub("\r","").html_safe if @song.body != nil %>');
})
</script>

app/views/songs/edit.html.erb
<div class="container">
	<% flash[:errors].try(:each) do |error|%>
	<div class="alert alert-warning alert-dismissable">
	  <button type="button" class="close" 
						data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= error %>
	</div>
	<% end %>
<h1>Edit <%= @song.title %> by <%= @song.artist %></h1>

<form action="<%= song_url(@song) %>" method="post" role="form">
	<input type="hidden" name="_method" value="put">
<%= render :partial => "form", :locals => { :song =>  @song } %>
</div>

app/views/songs/index.html.erb
<% @songs.sort_by! { |song| song.title }%>
<div class="container">
	
	<% if @is_search.nil? %>
		<h1>All Songs</h1>
	<% else %>
		<h1>Search Results for <em>'<%= @query %>'</em></h1>
	<% end %>
	<h4>
		<ul class="list-unstyled">
			<% @songs.each do |song| %>
			<li><%= link_to song.title, song_url(song) %> by <%= song.artist %></li>
			<% end %>
		</ul>
	</h4>
</div>

app/views/songs/new.html.erb
<div class="container">
	<% flash[:errors].try(:each) do |error|%>
	<div class="alert alert-warning alert-dismissable">
	  <button type="button" class="close" 
						data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= error %>
	</div>
	<% end %>
	<h1>Add a new Song</h1>
	
	<form action="<%= songs_url %>" method="post" role="form">
	<%= render :partial => "form", :locals => { :song =>  @song } %>
</div>

app/views/songs/show.html.erb
<script type="application/json" id="bootstrapped-song">
	<%= render(:file => 'songs/show', :formats => [:rabl]).html_safe %>
</script>

<script type="text/javascript">
	$(document).ready(function(){
	  LyricalMiracle.initialize();

		$(document).mousedown( function () {
			$('#annotate-button').remove();	
			$('.popover-link').popover('hide');
		});
		
	});
</script>

app/views/users/new.html.erb
<h1> Sign Up</h1>

<form action="/users" method="post">
  <label>Username: <input type="text" name="user[username]" value="<%= @user.username %>" /></label>
  <label>Password: <input type="password" name="user[password]" /></label>
  <button type="submit" class="btn btn-default">Sign Up</button>
</form>

<p>
  <%= link_to "Login", new_session_path %>
</p>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Page </h1>